# build stage
FROM node:20-alpine AS build-stage
WORKDIR /app
COPY package*.json ./
RUN apk add --no-cache bash gettext ca-certificates && \
    npm install && npm cache clean --force
COPY . .
EXPOSE 3000
CMD ["npm", "run", "dev"]
