apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: k8s-ingress-dashboard
build:
  artifacts:
    - image: shokohsc/k8s-ingress-dashboard
      context: .
      sync:
        infer:
          - src/**/*.js
          - src/**/*.vue
      docker:
        dockerfile: Dockerfile.dev
manifests:
  kustomize:
    paths:
      - k8s/base
deploy:
  kubectl: {}
profiles:
  - name: dev
    activation:
      - command: dev
    build:
      artifacts:
        - image: shokohsc/k8s-ingress-dashboard
          sync:
            infer:
              - src/**/*.js
              - src/**/*.vue
  - name: shokohsc
    build:
      artifacts:
        - image: shokohsc/k8s-ingress-dashboard
          sync:
            infer:
              - src/**/*.js
              - src/**/*.vue
          kaniko:
            useNewRun: true
            cache:
              repo: shokohsc/k8s-ingress-dashboard
            dockerfile: Dockerfile.dev
      cluster:
        dockerConfig:
          secretName: kaniko-secret
        namespace: kaniko
        pullSecretName: kaniko-secret
        resources:
          limits:
            cpu: "2"
            memory: 2Gi
          requests:
            cpu: "1"
            memory: 1Gi
    manifests:
      kustomize:
        paths:
          - k8s/overlays/shokohsc
    deploy:
      kubectl: {}
  - name: prod
    build:
      artifacts:
        - image: shokohsc/k8s-ingress-dashboard
          kaniko:
            useNewRun: true
            cache:
              repo: shokohsc/k8s-ingress-dashboard
            dockerfile: Dockerfile
            buildArgs:
              POD_NAME: '{{.GIT_COMMIT}}'
              SENTRY_AUTH_TOKEN: db6ff5f7b002322a0b6800027fa823d5faa131dc2535e060375d902728ea8353
              SENTRY_PROJECT: dashboard
      cluster:
        dockerConfig:
          secretName: kaniko-secret
        namespace: kaniko
        pullSecretName: kaniko-secret
        resources:
          limits:
            cpu: "2"
            memory: 2Gi
          requests:
            cpu: "1"
            memory: 1Gi