---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: dashboard
spec:
  selector:
    matchLabels:
      app: dashboard
  template:
    metadata:
      labels:
        app: dashboard
    spec:
      containers:
        - name: dashboard
          image: shokohsc/k8s-ingress-dashboard
          env:
            - name: ENV
              value: production
            - name: API_GATEWAY_HOST
              value: api.cluster.local
            - name: API_GATEWAY_PORT
              value: "80"
            - name: USE_SENTRY
              value: "false"
            - name: YOUTUBE_VIDEO_ID
              value: eEpEeyqGlxA
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          startupProbe:
            tcpSocket:
              port: http
          livenessProbe:
            tcpSocket:
              port: http
          readinessProbe:
            httpGet:
              port: http
              path: /
          resources:
            requests:
              cpu: 10m
              memory: 64M
            limits:
              cpu: 100m
              memory: 64M
