---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: k8s-ingress-dashboard
spec:
  template:
    spec:
      containers:
        - name: k8s-ingress-dashboard
          image: shokohsc/k8s-ingress-dashboard
          env:
            - name: ENV
              value: development
            - name: API_GATEWAY_HOST
              value: sidekick.shokohsc.home
            - name: API_GATEWAY_PORT
              value: "443"
            - name: USE_SENTRY
              value: "true"
            - name: SENTRY_DSN
              value: https://2f15ffed2e254ced911e78de9312afe0\@glitchtip.shokohsc.home/1
            - name: YOUTUBEVIDEOIDS
              value: 'eEpEeyqGlxA,9k4R3BhUi68,cQLa6lbZvzw,J2UyOTS3UCE,WA6irSA3SKc,Y1qQZbTF8iQ,rw7bxTqkYYs,BuIVgtAXW_8'
          resources:
            requests:
              cpu: 10m
              memory: 64M
            limits:
              cpu: 1000m
              memory: 256M
